version: '3.8'

services:
  donor:
    container_name: dornor
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./upload:/app/upload

  nginx:
    image: nginx:latest
    container_name: nginx-gateway-ai
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./upload:/usr/share/nginx/html/upload
    ports:
      - "3001:80"

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wj651213
      MYSQL_DATABASE: store
      MYSQL_PASSWORD: wj651213
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql